"""
Django settings for Profcess_Dev project.

Generated by 'django-admin startproject' using Django 2.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
TEMPLATE_DIR = os.path.join(BASE_DIR,'templates')



# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '&$c!ytv1yqj#5pf9+=)br#(ka10$yn)s1iu^fo9kd#tor#t)lz'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# ALLOWED_HOSTS = ['UATProfcess.pythonanywhere.com']
ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # "test_app",
    "accounts",
    #"applicant_app",
    "recruiter_app",
    "college_app",
    'phone_field',
    'crispy_forms',
    'six',
    'multiselectfield',
    'django_select2',
    'htmltopdf',
    'phonenumber_field',
    'csvimport.app.CSVImportConf',
    'applicant_app.apps.ApplicantAppConfig',
    'paywix',
    'widget_tweaks',
    'django.contrib.sites',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    'allauth.socialaccount.providers.linkedin_oauth2',
    'social',
    'accounts_social',
    'chat',
    'rest_framework',
]
AUTHENTICATION_BACKENDS = [

    # Needed to login by username in Django admin, regardless of `allauth`
    'django.contrib.auth.backends.ModelBackend',

    # `allauth` specific authentication methods, such as login by e-mail
    'allauth.account.auth_backends.AuthenticationBackend',

]


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Profcess_Dev.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [TEMPLATE_DIR,],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'accounts.context_processors.Fcontact'
            ],
        },
    },
]

WSGI_APPLICATION = 'Profcess_Dev.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases


DATABASES = { 'default': { 'ENGINE': 'django.db.backends.sqlite3', 'NAME': os.path.join(BASE_DIR, 'db.sqlite3'), } }
"""
DATABASES = {
#<<<<<<< HEAD
#<<<<<<< HEAD
#    'default': {
#=======
#     'default': {
#>>>>>>> f7ef2afefe643ae4581f638c22e1432196296096
#=======
#      'default': {
# # #>>>>>>> f7ef2afefe643ae4581f638c22e1432196296096
#          'ENGINE': 'django.db.backends.sqlite3',
#          'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
#      }
#<<<<<<< HEAD
'default': {
      #
      # 'ENGINE': 'django.db.backends.mysql',
      # 'NAME': 'UATprofcess$profcess',
      # 'USER': 'UATprofcess',
      # 'PASSWORD': 'Horizon@13',
      # 'HOST': 'UATprofcess.mysql.pythonanywhere-services.com',
      # 'PORT': '3306',

        'ENGINE': 'django.db.backends.sqlite3', 'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
      }
      
#>>>>>>> f7ef2afefe643ae4581f638c22e1432196296096
    #    'ENGINE': 'django.db.backends.mysql',
    #    'NAME': 'database2.3',
    #    'USER': 'root',
    #     'PASSWORD': '',
    #     'HOST': 'localhost',
    #     'PORT': '3306',}
#<<<<<<< HEAD
#>>>>>>> f7ef2afefe643ae4581f638c22e1432196296096
#=======
#>>>>>>> f7ef2afefe643ae4581f638c22e1432196296096
    #},
#=======
    # 'default': {
    #    'ENGINE': 'django.db.backends.mysql',
    #    'NAME': 'database2.0',
    #    'USER': 'root',
    #     'PASSWORD': '',
    #     'HOST': 'localhost',
    #     'PORT': '3306',
    # },
#>>>>>>> a0047ef3c5d668716f4d8fece663933083a68259
}
"""

# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

# AUTH_USER_MODEL = "test_app.User"
AUTH_USER_MODEL = "accounts.ProfcessUser"

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = '/static/'
MEDIA_URL = '/media/'

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
]

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
LOGIN_REDIRECT_URL = "index"
LOGOUT_REDIRECT_URL = "index"

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
#EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'profcess1@gmail.com'#'verification@profcess.com''
EMAIL_HOST_PASSWORD = 'test@12345678'#'profcess123*'#
DEFAULT_FROM_EMAIL = 'profcesscompany@gmail.com '


PAYU_CONFIG = {
    "merchant_key": "4C7QRweG",
    "merchant_salt": "BAMFQEqB1I",
    "mode": "test",
    "success_url": "http://127.0.0.1:8000/recruiter/success",
    "failure_url": "http://127.0.0.1:8000/recruiter/failure"
}
SITE_ID =14
LOGIN_REDIRECT_URL = '/'
SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'SCOPE': [
            'profile',
            'email',
        ],
        'AUTH_PARAMS': {
            'access_type': 'online',
        }
    }
}
