# Generated by Django 2.2.22 on 2021-06-23 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applicant_app', '0001_initial'),
        ('accounts', '0001_initial'),
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='profcessuser',
            name='shortlist_can',
            field=models.ManyToManyField(blank=True, related_name='shortlist_can', to='applicant_app.ApplicantUserProfile'),
        ),
        migrations.AddField(
            model_name='profcessuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
    ]
